package]
name    = "sabo_os_v3"
version = "3.0.0"
edition = "2021"

# Requer nightly para inline ASM completo
# rustup override set nightly

[[bin]]
name = "sabo_os_v3"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }

[profile.release]
opt-level     = 3
lto           = true
codegen-units = 1
panic         = "abort"
strip         = true

# Para rodar:
# RUSTFLAGS="-C target-cpu=native" cargo +nightly run --release
